version: '3.0'

services:
  api:
    build:
        context: .
        dockerfile: ./docker/api/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    command: bash -c "bundle exec rails db:migrate && bundle exec rails s -p 80 -b 0.0.0.0"
  db:
    image: postgres
    env_file:
      - .env
  nginx:
    depends_on:
      - api
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
  redis:
    image: redis
