version: '3.0'

services:
  api:
    build:
        context: .
        dockerfile: ./docker/api/Dockerfile
    image: blockadaby/api
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - 80:80
    command: bash -c "rm -rf /app/tmp/pids/server.pid && rails db:migrate && rails s -p 80 -b 0.0.0.0"
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    image: postgres
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - 6379:6379
  sidekiq:
    image: blockadaby/api
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
      - db
    env_file:
      - .env
  # nginx:
  #   depends_on:
  #     - api
  #   build:
  #     context: .
  #     dockerfile: ./docker/nginx/Dockerfile
  #   ports:
  #     - 80:80
